[tools]
java = "temurin-21.0.2+13.0.LTS"
clojure = "1.12.3.1577"
babashka = "1.12.209"
clj-kondo = "2025.10.23"
cljfmt = "0.15.4"
tailwindcss = "4.1.17"

[alias]
cljfmt = "asdf:https://github.com/b-social/asdf-cljfmt"
tailwindcss = "asdf:https://github.com/virtualstaticvoid/asdf-tailwindcss"
